version: "3"

services:
  webserver:
    build: 
      context: ./docker/web
    depends_on:
      - mitmproxy
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    environment:
      - http_proxy=http://mitmproxy:8080
      - HTTPS_PROXY=http://mitmproxy:8080
      - XDEBUG_CONFIG="remote_host=localhost remote_port=9000 remote_enable=1"
    links:
      - mitmproxy
    volumes: 
      - ./www:/var/www/html
      - ./configs/web/vhosts:/etc/apache2/sites-enabled/
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./configs/php/patch.php:/usr/local/bin/patch.php
      - ./configs/php/unpatch.php:/usr/local/bin/unpatch.php
      - ./logs:/var/log/phishpond/
      - mitm-volume:/usr/local/share/ca-certificates/extra/
    command: >
      bash -c "cp /usr/local/share/ca-certificates/extra/mitmproxy-ca-cert.{pem,crt} &&
      update-ca-certificates --verbose && 
      chmod -R 777 /var/log/phishpond &&
      apache2-foreground"
  mitmproxy:
    build:
      context: ./docker/mitmproxy
    container_name: 'mitmproxy'
    command: bash -c "mitmweb --web-host 0.0.0.0 --set confdir=/home/mitmproxy/.mitmproxy --set relax_http_form_validation" 
    ports:
      - "8080:8081" 
    tty: true
    volumes:
      - mitm-volume:/home/mitmproxy/.mitmproxy/
      - ./configs/mitmproxy/config.yaml:/home/mitmproxy/.mitmproxy/config.yaml
volumes:
  mitm-volume:
